import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const scrapeMutation = api.example.scrape.useMutation();
  const sanitizeMutation = api.example.sanitize.useMutation();
  const { data: devices, refetch } = api.example.get.useQuery({});

  function sanitize() {
    if (!confirm("Delete all devices?")) return;
    sanitizeMutation.mutate();
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() =>
            scrapeMutation.mutate(undefined, {
              onSuccess() {
                refetch();
              },
            })
          }
        >
          Scrape
        </button>

        <table className={styles.table}>
          <thead>
            <th>TID</th>
            <th>Company</th>
            <th>Name</th>
            <th>Model/part number</th>
            <th>Product revision</th>
            <th>USB connector</th>
            <th>Total wattage</th>
          </thead>
          <tbody>
            {devices?.map((device) => {
              return (
                <tr key={device.tid}>
                  <td>{device.tid}</td>
                  <td>{device.companyName}</td>
                  <td>{device.name}</td>
                  <td>{device.modelPartNumber}</td>
                  <td>{device.productRevision}</td>
                  <td>{device.usbConnector}</td>
                  <td>{device.totalWattageFromPorts}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
